FROM node:alpine AS install
WORKDIR /app

RUN corepack enable && corepack prepare pnpm@latest --activate

COPY package.json .
COPY pnpm-lock.yaml .
COPY . .

RUN pnpm install --frozen-lockfile

CMD ["pnpm", "dev", "--host"]

