version: "3"
services:
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    depends_on:
      - backend
    profiles:
      - dev
  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    depends_on:
      - db
  frontend-prod:
    build:
      context: ./frontend
      dockerfile: Dockerfile.main
    ports:
      - 3000:3000
    depends_on:
      - backend
    profiles:
      - prod
  backend-prod:
    build:
      context: ./backend
      dockerfile: Dockerfile.main
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: ghcr.io/tursodatabase/libsql-server:latest
    platform: linux/amd64
    ports:
      - "8080:8080"
      - "5001:5001"
    # environment:
    #   - SQLD_NODE=primary
    volumes:
      - ./data/libsql:/var/lib/sqld
