version: "3"
services:
  backend: 
    build: 
      context: ./backend
      dockerfile: Dockerfile 
    ports:
      - 8000:8000
  db:
    image: ghcr.io/tursodatabase/libsql-server:latest
    platform: linux/amd64
    ports:
      - "8080:8080"
      - "5001:5001"
    # environment:
    #   - SQLD_NODE=primary
    volumes:
      - ./data/libsql:/var/lib/sqld