FROM denoland/deno:latest AS installer
WORKDIR /app

COPY --chown=deno:deno ./deno.json .
COPY --chown=deno:deno ./main.ts .
COPY --chown=deno:deno ./src .

RUN deno install 
RUN deno cache main.ts

FROM denoland/deno:latest AS dev
WORKDIR /app
COPY --from=installer /app .

USER deno

# Run the app
CMD ["deno",  "run", "--allow-net","--allow-env","--env", "--watch" , "main.ts"]
 