name: Playwright Tests
on:
  push:
    branches: [ main, develop]
  pull_request:
    branches: [ main, develop]
jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    env: 
      DENO_DIR: $HOME/.deno
    steps:
    - uses: actions/checkout@v4
    - uses: denoland/setup-deno@v2
      with:
        deno-version: v2.2.9 # Run with latest stable Deno.
        path: ${{env.DENO_DIR}}
        key: cache
    - name: Install Deno Modules
      run: deno install
    - name: Install Playwright Browsers
      run: deno run npm:playwright install --with-deps 
    # - name: Install dependencies
    #   run: npm install -g pnpm && pnpm install
    # - name: Install Playwright Browsers
      # run: pnpm exec playwright install --with-deps
    - name: Run Playwright tests
      run: deno run test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
