
name: Tests Frontend 
on:
  push:
    branches: 
    - main
    - qa
    - dev
    paths:
      - "frontend/**"
  pull_request:
    branches: 
    - main
    - qa
    - dev
    paths:
      - "frontend/**"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.12.0'
      - name: Install dependencies
        run: npm install -g pnpm && pnpm install